<?php

namespace ShopBundle\Repository;

/**
 * SunglassesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SunglassesRepository extends \Doctrine\ORM\EntityRepository
{
}
