admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /shop

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout/
